/*******************************************************************************
 *
 * $Id: codefile.c 3576 2012-07-31 12:56:35Z fpz $
 *
 * Author: Kari Keinanen, VTT Technical Research Centre of Finland
 * -------
 *
 * Date:   29.01.2007
 * -----
 *
 *******************************************************************************/

#include "codefile.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "ctinfo.h"
#include "str.h"
#include "memory.h"
#include "globals.h"
#include "mutil.h"

static FILE *hdrFile = NULL;
static FILE *srcFile = NULL;

static unsigned int entryIndex = 1;
static unsigned int interfaceIndex = 0;
static unsigned int indentLevel = 0;

static void writeIfndefStart(const char *base)
{
  unsigned int length = strlen(base);
  char *defName = (char *)MEMmalloc(length+1);
  int i;

  for(i = 0; i < length; ++i) {
    defName[i] = toupper(base[i]);
  }
  defName[i] = 0;

  fprintf(hdrFile, "#ifndef _%s_H_\n", defName);
  fprintf(hdrFile, "#define _%s_H_\n\n", defName);

  MEMfree(defName);
}

static void writeIfdefStop()
{
  fprintf(hdrFile, "\n\n#endif\n");
}

static void writeHdrGenerationInfo(const char *base)
{
  fprintf(hdrFile, "/**\n");
  fprintf(hdrFile, " * @file %s.h\n", base);
  fprintf(hdrFile, " *\n");
  fprintf(hdrFile, " * Header definitions of compiled snet-file for runtime.\n");
  fprintf(hdrFile, " *\n");
  fprintf(hdrFile, " * THIS FILE HAS BEEN GENERATED.\n");
  fprintf(hdrFile, " * DO NOT EDIT THIS FILE.\n");
  fprintf(hdrFile, " * EDIT THE ORIGINAL SNET-SOURCE FILE %s.snet INSTEAD!\n", base);
  fprintf(hdrFile, " *\n");
  fprintf(hdrFile, " * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!\n");
  fprintf(hdrFile, " *\n");
  fprintf(hdrFile, "*/\n\n");
}

static void writeSrcGenerationInfo(const char *base)
{
  fprintf(srcFile, "/**\n");
  fprintf(srcFile, " * @file %s.c\n", base);
  fprintf(srcFile, " *\n");
  fprintf(srcFile, " * Source code of compiled snet-file for runtime.\n");
  fprintf(srcFile, " *\n");
  fprintf(srcFile, " * THIS FILE HAS BEEN GENERATED.\n");
  fprintf(srcFile, " * DO NOT EDIT THIS FILE.\n");
  fprintf(srcFile, " * EDIT THE ORIGINAL SNET-SOURCE FILE %s.snet INSTEAD!\n", base);
  fprintf(srcFile, " *\n");
  fprintf(srcFile, " * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!\n");
  fprintf(srcFile, " *\n");
  fprintf(srcFile, "*/\n\n");
}

bool CODEFILEopenFiles(const char *base)
{
  char *fileName = STRcat(base, ".c");

  CTInote("Opening source file %s for code generation\n", fileName);
  if((srcFile = fopen(fileName, "w")) == NULL) {
    CTIerror(CTI_ERRNO_FILE_ACCESS_ERROR, "Source file %s open failed\n", fileName);
    return FALSE;
  }
  writeSrcGenerationInfo(base);

  fileName[strlen(fileName)-1] = 'h';
  CTInote("Opening header file %s for code generation\n", fileName);
  if((hdrFile = fopen(fileName, "w")) == NULL) {
    CTIerror(CTI_ERRNO_FILE_ACCESS_ERROR, "Header file %s open failed\n", fileName);
    return FALSE;
  }
  writeHdrGenerationInfo(base);

  CODEFILEwriteSrcInclude(base, "h");

  writeIfndefStart(base);
  CODEFILEwriteHdrInclude("snetentities", "h");
  CODEFILEwriteHdrInclude("distribution", "h");

  MEMfree(fileName);

  return TRUE;
}

void CODEFILEcloseFiles()
{
  writeIfdefStop();
  fprintf(hdrFile, "\n");
  fprintf(srcFile, "\n");
  fclose(hdrFile);
  fclose(srcFile);
}

static const char *indent(unsigned int level)
{
  static char ind[100];
  unsigned int i;

  ind[0] = 0;

  for(i = 0; i < level; ++i) {
    strcat(ind, "  ");
  }

  return ind;
}

void CODEFILEwriteNewlineAndIndent()
{
  fprintf(srcFile, "\n%s", indent(indentLevel));
}

void increaseIndentLevel()
{
  indentLevel++;
}
void decreaseIndentLevel()
{
  if(indentLevel > 0)
    indentLevel--;
}
void increaseIndentLevels(unsigned int levels)
{
  indentLevel += levels;
}
void decreaseIndentLevels(unsigned int levels)
{
  if(indentLevel - levels > 0)
    indentLevel -= levels;
}

void CODEFILEwriteHdrInclude(const char *fileBase, const char *fileType)
{
  fprintf(hdrFile, "#include \"%s.%s\"\n", fileBase, fileType);
}

void CODEFILEwriteSrcInclude(const char *fileBase, const char *fileType)
{
  fprintf(srcFile, "#include \"%s.%s\"\n", fileBase, fileType);
}

void CODEFILEwriteGetRecord()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "rec = SNetHndGetRecord(hnd);\n");
}

void CODEFILEwriteOutBufDecl()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "snet_stream_t *out_buf = NULL;");
}

void CODEFILEwriteOutTypeDecl()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "snet_typeencoding_t *out_type = NULL;");
}


void CODEFILEwriteBoxSignEncStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_sign = SNetTencBoxSignEncode( out_type");
  increaseIndentLevels(6);
}

void CODEFILEwriteBoxSignDecl()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "snet_box_sign_t *out_sign = NULL;");
}

void CODEFILEwriteBoxSignField()
{
  fprintf(srcFile, "field");
}

void CODEFILEwriteBoxSignTag()
{
  fprintf(srcFile, "tag");
}

void CODEFILEwriteBoxSignBTag()
{
  fprintf(srcFile, "btag");
}

void CODEFILEwriteOutBufReturn()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "return (out_buf);\n");
}

void CODEFILEwriteNoneDefine()
{
  fprintf(hdrFile, "\n#define E__%s__NONE 0", global.filebase);
}

void CODEFILEwriteFieldDefine(const char *pkg, const char *field)
{
  if(pkg == NULL) {
    fprintf(hdrFile, "\n#define F__");
    fprintf(hdrFile, "%s__", global.filebase);
    fprintf(hdrFile, "%s %d", field, entryIndex);
    entryIndex++;
  }
}

void CODEFILEwriteStagDefine(const char *pkg, const char *stag)
{
  if(pkg == NULL) {
    fprintf(hdrFile, "\n#define T__");
    fprintf(hdrFile, "%s__", global.filebase);
    fprintf(hdrFile, "%s %d", stag, entryIndex);
    entryIndex++;
  }
}

void CODEFILEwriteBtagDefine(const char *pkg, const char *btag)
{
  if(pkg == NULL) {
    fprintf(hdrFile, "\n#define B__");
    fprintf(hdrFile, "%s__", global.filebase);
    fprintf(hdrFile, "%s %d", btag, entryIndex);
    entryIndex++;
  }
}

void CODEFILEwriteNumberOfLabels(){
  fprintf(hdrFile, "\n\n#define SNET__%s__NUMBER_OF_LABELS %d\n\n", global.filebase, entryIndex);
}

void CODEFILEwriteInterfaceDefine(const char *interface)
{
  fprintf(hdrFile, "\n#define I__");
  fprintf(hdrFile, "%s__", global.filebase);
  fprintf(hdrFile, "%s %d", interface, interfaceIndex);
  interfaceIndex++;
}

void CODEFILEwriteNumberOfInterfaces(){
  fprintf(hdrFile, "\n\n#define SNET__%s__NUMBER_OF_INTERFACES %d\n\n", global.filebase, interfaceIndex);
}


void CODEFILEwriteTopLevelNetDeclaration(const char *net)
{
  fprintf(hdrFile, "\n\nextern snet_stream_t *SNet__%s___%s(snet_stream_t *in_buf, snet_info_t *info, int location);", global.filebase, net);
}

void CODEFILEwriteBoxStart(const char *box)
{
  fprintf(srcFile, "\nstatic snet_handle_t *SNet__%s(snet_handle_t *hnd)\n{", box);
  increaseIndentLevel();
}

void CODEFILEwriteRecDecl()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "struct record *rec = NULL;");
}

void CODEFILEwriteScopeStop()
{
  fprintf(srcFile, "}\n");
  decreaseIndentLevel();
}

void CODEFILEwriteNetStart(const char *net)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
}

void CODEFILEwriteTopLevelNetStart(const char *net)
{
  fprintf(srcFile, "\nsnet_stream_t *SNet__%s___%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", global.filebase, net);
  increaseIndentLevel();
}

void CODEFILEwriteNetStarIncStart(const char *net)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____STAR_INCARNATE_%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
}


void CODEFILEwriteBoxCompStart(const char *box)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "return(SNetCall__%s(hnd", box);
  increaseIndentLevels(6);
}

void CODEFILEwriteBoxCompField(const char *field)
{
  fprintf(srcFile, "field_%s", field);
}

void CODEFILEwriteBoxCompStag(const char *stag)
{
  fprintf(srcFile, "stag_%s", stag);
}

void CODEFILEwriteBoxCompBtag(const char *btag)
{
  fprintf(srcFile, "btag_%s", btag);
}

void CODEFILEwriteBoxFullStop()
{
  fprintf(srcFile, "));\n");
  decreaseIndentLevels(6);
}

void CODEFILEwriteFunctionFullStop()
{
  fprintf(srcFile, ");\n");
  decreaseIndentLevels(6);
}

void CODEFILEwriteSnetEntity(const char *pkg, const char *entity)
{
  CODEFILEwriteNewlineAndIndent();

  if(pkg == NULL) {
    fprintf(srcFile, "&SNet__%s", entity);
  }
  else{
    fprintf(srcFile, "&SNet__%s___%s", pkg, entity);
  }
}

void CODEFILEwriteBoxname( const char *name)
{
  fprintf( srcFile, "\"%s\"", name);
}

void CODEFILEwriteRealmCreate(const char *name)
{
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "&SNetExeRealm_create__%s", name);
}

void CODEFILEwriteRealmUpdate(const char *name)
{
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "&SNetExeRealm_update__%s", name);
}

void CODEFILEwriteRealmDestroy(const char *name)
{
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "&SNetExeRealm_destroy__%s", name);
}

void CODEFILEwriteSnetBoxStart()
{
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "out_buf = SNetBox(in_buf");

  increaseIndentLevels(6);
}

void CODEFILEwriteSnetBoxStop()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_sign);\n");
  decreaseIndentLevels(6);
}

void CODEFILEwriteSnetAlias(const char *pkg, const char *net, int location)
{
  CODEFILEwriteNewlineAndIndent();

  if(pkg == NULL) {
    fprintf(srcFile, "out_buf = SNetAlias(in_buf");
    CODEFILEwriteLocation(location);
    fprintf(srcFile, ", &SNet__%s);\n", net);
  }
  else{
    fprintf(srcFile, "out_buf = SNetAlias(in_buf");
    CODEFILEwriteLocation(location);
    fprintf(srcFile, ", &SNet__%s___%s);\n", pkg, net);
  }
}

void CODEFILEwriteSnetSerialStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetSerial(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetSplitStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetSplit(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetSplitDetStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetSplitDet(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetLocSplitStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetLocSplit(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetLocSplitDetStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetLocSplitDet(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetStarStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetStar(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetStarDetStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetStarDet(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetStarIncEntity(const char *entity)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "&SNet____STAR_INCARNATE_%s", entity);
}

void CODEFILEwriteSnetStarIncStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetStarIncarnate(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetStarDetIncStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetStarDetIncarnate(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetFeedbackStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetFeedback(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetSyncStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetSync(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetFilterStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetFilter(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetTranslateStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetTranslate(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetParallelStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetParallel(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteSnetParallelDetStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetParallelDet(in_buf");
  increaseIndentLevels(6);
}

void CODEFILEwriteVariantListStart(unsigned int variantCount)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetVariantListCreate(%u", variantCount);
  increaseIndentLevel();
}

void CODEFILEwriteVariantListListStart(unsigned int variantListCount)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetVariantListListCreate(%u", variantListCount);
  increaseIndentLevel();
}

void CODEFILEwriteFunctionStop()
{
  fprintf(srcFile, ")");
  decreaseIndentLevel();
}

void CODEFILEwriteEmptyVariant()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetVariantCreateEmpty()");
}

void CODEFILEwriteVariantStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetVariantCreate(");
  increaseIndentLevel();
}

void CODEFILEwriteIntListStart(unsigned int entryCount)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetIntListCreate(%u", entryCount);
  increaseIndentLevel();
}

void CODEFILEwriteIntListListStart(unsigned int entryCount)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetIntListListCreate(%u", entryCount);
  increaseIndentLevel();
}

void CODEFILEwriteTakeField(const char *pkg, const char *field)
{
  CODEFILEwriteNewlineAndIndent();

  if(pkg != NULL){
    fprintf(srcFile, "field_%s = SNetRefTakeData(SNetRecTakeField(rec, F__%s__%s));\n", field, pkg, field);
  } else{
    fprintf(srcFile, "field_%s = SNetRefTakeData(SNetRecTakeField(rec, F__%s__%s));\n", field, global.filebase, field);
  }
}

void CODEFILEwriteGetField(const char *pkg, const char *field)
{
  CODEFILEwriteNewlineAndIndent();

  if(pkg != NULL){
    fprintf(srcFile, "field_%s = SNetDistribRefTakeData(SNetRecGetField(rec, F__%s__%s));\n", field, pkg, field);
  } else{
    fprintf(srcFile, "field_%s = SNetDistribRefTakeData(SNetRecGetField(rec, F__%s__%s));\n", field, global.filebase, field);
  }
}

void CODEFILEwriteTakeStag(const char *pkg, const char *stag)
{
  CODEFILEwriteNewlineAndIndent();

  if(pkg != NULL){
    fprintf(srcFile, "stag_%s = SNetRecTakeTag(rec, T__%s__%s);\n", stag, pkg, stag);
  }
  else{
    fprintf(srcFile, "stag_%s = SNetRecTakeTag(rec, T__%s__%s);\n", stag, global.filebase, stag);
  }
}

void CODEFILEwriteGetStag(const char *pkg, const char *stag)
{
  CODEFILEwriteNewlineAndIndent();

  if(pkg != NULL){
    fprintf(srcFile, "stag_%s = SNetRecGetTag(rec, T__%s__%s);\n", stag, pkg, stag);
  }
  else{
    fprintf(srcFile, "stag_%s = SNetRecGetTag(rec, T__%s__%s);\n", stag, global.filebase, stag);
  }
}

void CODEFILEwriteTakeBtag(const char *pkg, const char *btag)
{
  CODEFILEwriteNewlineAndIndent();

  if(pkg != NULL){
    fprintf(srcFile, "btag_%s = SNetRecTakeBTag(rec, B__%s__%s)\n;", btag, pkg, btag);
  }
  else{
    fprintf(srcFile, "btag_%s = SNetRecTakeBTag(rec, B__%s__%s)\n;", btag, global.filebase, btag);
  }
}


void CODEFILEwriteSnetEconsti(int consti)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetEconsti( %d)", consti);
}

void CODEFILEwriteSnetEconstbTrue()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetEconstb( true)");
}

void CODEFILEwriteSnetEStagStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetEtag( ");
  increaseIndentLevel();
}

void CODEFILEwriteSnetEBtagStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetEbtag( ");
  increaseIndentLevel();
}

void CODEFILEwriteSnetEStart(const char *operator)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetE%s( ", operator);
  increaseIndentLevel();
}

void CODEFILEwriteNext()
{
  fprintf(srcFile, ", ");
}

void CODEFILEwriteField(const char *pkg, const char *field)
{
  if(pkg == NULL) {
    fprintf(srcFile, "F__%s__%s", global.filebase, field);
  }
  else {
    fprintf(srcFile, "F__%s__%s", pkg, field);
  }
}

void CODEFILEwriteStag(const char *pkg, const char *stag)
{
  if(pkg == NULL) {
    fprintf(srcFile, "T__%s__%s", global.filebase, stag);
  }
  else {
    fprintf(srcFile, "T__%s__%s", pkg, stag);
  }
}

void CODEFILEwriteBtag(const char *pkg, const char *btag)
{
  if(pkg == NULL) {
    fprintf(srcFile, "B__%s__%s", global.filebase, btag);
  }
  else {
    fprintf(srcFile, "B__%s__%s", pkg, btag);
  }
}

void CODEFILEwriteNULL()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "NULL");
}

void CODEFILEwriteExprListStart(unsigned int entryCount)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetExprListCreate(%u", entryCount);
  increaseIndentLevel();
}
void CODEFILEwriteFilterInstrListListStart(unsigned int entryCount)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetFilterInstrListListCreate(%u", entryCount);
  increaseIndentLevel();
}
void CODEFILEwriteFilterInstrListStart(unsigned int entryCount)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetFilterInstrListCreate(%u", entryCount);
  increaseIndentLevel();
}

void CODEFILEwriteInitField(const char *field)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "void *field_%s = NULL;", field);
}

void CODEFILEwriteInitStag(const char *stag)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "int stag_%s = 0;", stag);
}

void CODEFILEwriteInitBtag(const char *btag)
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "int btag_%s = 0;", btag);
}

void CODEFILEwriteNewline()
{
  fprintf(srcFile, "\n");
}

void CODEFILEwriteFilterInstrFieldStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetCreateFilterInstruction(snet_field");
  increaseIndentLevel();
}

void CODEFILEwriteFilterInstrTagStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetCreateFilterInstruction(snet_tag");
  increaseIndentLevel();
}

void CODEFILEwriteFilterInstrBtagStart()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetCreateFilterInstruction(snet_btag");
  increaseIndentLevel();
}

void CODEFILEwriteFilterInstrCreateRecord()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetCreateFilterInstruction(create_record)");
}

void CODEFILEwriteShieldInPart1(const char *net, int location)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____SHIELD_IN__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
  CODEFILEwriteOutBufDecl();
  CODEFILEwriteNewline();
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetNameShift(in_buf");
  CODEFILEwriteLocation(location);
  fprintf(srcFile, ", SNET__%s__NUMBER_OF_LABELS,", global.filebase);
  increaseIndentLevels(6);
}

void CODEFILEwriteShieldBodyPart1(const char *net, int location)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____SHIELD_BODY__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
  CODEFILEwriteOutBufDecl();
  CODEFILEwriteNewline();
  CODEFILEwriteSnetSerialStart();

  CODEFILEwriteLocation(location);

  CODEFILEwriteNext();
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "&SNet____SHIELD_IN__%s", net);
  CODEFILEwriteNext();
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "&SNet__%s___IN", net);

}

void CODEFILEwriteShieldOutPart1(const char *net, int location)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____SHIELD_OUT__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
  CODEFILEwriteOutBufDecl();
  CODEFILEwriteNewline();
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "out_buf = SNetNameShift(in_buf");
  CODEFILEwriteLocation(location);
  fprintf(srcFile, ", -SNET__%s__NUMBER_OF_LABELS,", global.filebase);
  increaseIndentLevels(6);
}

void CODEFILEwriteShieldPart2(void)
{
  CODEFILEwriteFunctionFullStop();
  CODEFILEwriteOutBufReturn();
  CODEFILEwriteScopeStop();
}

void CODEFILEwriteShieldTopLevelNet(const char *net, int location)
{
  CODEFILEwriteTopLevelNetStart(net);
  CODEFILEwriteOutBufDecl();
  CODEFILEwriteSnetSerialStart();

  CODEFILEwriteLocation(location);

  CODEFILEwriteNext();
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "&SNet____SHIELD_BODY__%s,", net);
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "&SNet____SHIELD_OUT__%s", net);
  CODEFILEwriteShieldPart2();
}


void CODEFILEwriteShieldNet(const char *net, int location)
{
  CODEFILEwriteNetStart(net);
  CODEFILEwriteOutBufDecl();
  CODEFILEwriteSnetSerialStart();

  CODEFILEwriteLocation(location);

  CODEFILEwriteNext();
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "&SNet____SHIELD_BODY__%s,", net);
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "&SNet____SHIELD_OUT__%s", net);
  CODEFILEwriteShieldPart2();
}

void CODEFILEwriteObservedNetStart(const char *net){
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____OBSERVED__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
}

void CODEFILEwriteSocketObserverBefore(const char *net, const char *realname,
				       const char *interactive, const char *data, const char *code,
				       const char *address, const char *port)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____OBSERVER__BEFORE__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
  CODEFILEwriteOutBufDecl();
  CODEFILEwriteNewline();
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "out_buf = SNetObserverSocketBox(in_buf, info, location, ");

  increaseIndentLevels(6);

  CODEFILEwriteNewlineAndIndent();

  if(address != NULL){
    fprintf(srcFile, "\"%s\", ", address);
  }else{
    fprintf(srcFile, "\"localhost\", ");
  }

  CODEFILEwriteNewlineAndIndent();

  if(port != NULL) {
    fprintf(srcFile, "%s, ", port);
  } else {
    fprintf(srcFile, "%s, ", METADATA_VALUE_OBSERVER_DEFAULT_PORT);
  }

  CODEFILEwriteNewlineAndIndent();

  if(interactive != NULL){
    fprintf(srcFile, "true, ");
  } else{
    fprintf(srcFile, "false, ");
  }

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "\"%s\", ", realname);

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNET_OBSERVERS_TYPE_BEFORE, ");

  CODEFILEwriteNewlineAndIndent();

  if(STReq(data, METADATA_VALUE_OBSERVER_DATA_LEVEL_ALLVALUES)){
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_ALLVALUES, ");
  }else if(STReq(data, METADATA_VALUE_OBSERVER_DATA_LEVEL_TAGVALUES)){
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_TAGVALUES, ");
  }else{
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_LABELS, ");
  }

  CODEFILEwriteNewlineAndIndent();
  if(code != NULL){
    fprintf(srcFile, "\"%s\");", code);
  }else {
    fprintf(srcFile, "NULL);");
  }

  decreaseIndentLevels(6);

  CODEFILEwriteNewline();
  CODEFILEwriteOutBufReturn();
  CODEFILEwriteScopeStop();

}


void CODEFILEwriteSocketObserverAfter(const char *net, const char *realname, const char *interactive,
				      const char *data, const char *code, const char *address, const char *port)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____OBSERVER__AFTER__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);

  increaseIndentLevel();
  CODEFILEwriteOutBufDecl();
  CODEFILEwriteNewline();
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "out_buf = SNetObserverSocketBox(in_buf, info, location, ");

  increaseIndentLevels(6);

  CODEFILEwriteNewlineAndIndent();

  if(address != NULL){
    fprintf(srcFile, "\"%s\", ", address);
  }else{
    fprintf(srcFile, "\"localhost\", ");
  }

  CODEFILEwriteNewlineAndIndent();

  if(port != NULL) {
    fprintf(srcFile, "%s, ", port);
  } else {
    fprintf(srcFile, "%s, ", METADATA_VALUE_OBSERVER_DEFAULT_PORT);
  }

  CODEFILEwriteNewlineAndIndent();

  if(interactive != NULL){
    fprintf(srcFile, "true, ");
  } else{
    fprintf(srcFile, "false, ");
  }

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "\"%s\", ", realname);

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNET_OBSERVERS_TYPE_AFTER, ");

  CODEFILEwriteNewlineAndIndent();

  if(STReq(data, METADATA_VALUE_OBSERVER_DATA_LEVEL_ALLVALUES)){
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_ALLVALUES, ");
  }else if(STReq(data, METADATA_VALUE_OBSERVER_DATA_LEVEL_TAGVALUES)){
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_TAGVALUES, ");
  }else{
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_LABELS, ");
  }

  CODEFILEwriteNewlineAndIndent();
  if(code != NULL){
    fprintf(srcFile, "\"%s\");", code);
  }else {
    fprintf(srcFile, "NULL);");
  }

  decreaseIndentLevels(6);

  CODEFILEwriteNewline();
  CODEFILEwriteOutBufReturn();
  CODEFILEwriteScopeStop();
}

void CODEFILEwriteFileObserverBefore(const char *net, const char *realname, const char *data,
				     const char *code, const char *file)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____OBSERVER__BEFORE__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
  CODEFILEwriteOutBufDecl();
  CODEFILEwriteNewline();
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "out_buf = SNetObserverFileBox(in_buf, info, location, ");

  increaseIndentLevels(6);

  CODEFILEwriteNewlineAndIndent();

  if(file != NULL){
    fprintf(srcFile, "\"%s\", ", file);
  }else{
    fprintf(srcFile, "\"NULL\", ");
  }

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "\"%s\", ", realname);

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNET_OBSERVERS_TYPE_BEFORE, ");

  CODEFILEwriteNewlineAndIndent();

  if(STReq(data, METADATA_VALUE_OBSERVER_DATA_LEVEL_ALLVALUES)){
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_ALLVALUES, ");
  }else if(STReq(data, METADATA_VALUE_OBSERVER_DATA_LEVEL_TAGVALUES)){
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_TAGVALUES, ");
  }else{
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_LABELS, ");
  }

  CODEFILEwriteNewlineAndIndent();
  if(code != NULL){
    fprintf(srcFile, "\"%s\");", code);
  }else {
    fprintf(srcFile, "NULL);");
  }

  decreaseIndentLevels(6);

  CODEFILEwriteNewline();
  CODEFILEwriteOutBufReturn();
  CODEFILEwriteScopeStop();
}

void CODEFILEwriteFileObserverAfter(const char *net, const char *realname, const char *data,
				    const char *code, const char *file)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____OBSERVER__AFTER__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
  CODEFILEwriteOutBufDecl();
  CODEFILEwriteNewline();
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "out_buf = SNetObserverFileBox(in_buf, info, location, ");

  increaseIndentLevels(6);

  CODEFILEwriteNewlineAndIndent();
  if(file != NULL){
    fprintf(srcFile, "\"%s\", ", file);
  }else{
    fprintf(srcFile, "\"NULL\", ");
  }

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "\"%s\", ", realname);

  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "SNET_OBSERVERS_TYPE_AFTER, ");

  CODEFILEwriteNewlineAndIndent();

  if(STReq(data, METADATA_VALUE_OBSERVER_DATA_LEVEL_ALLVALUES)){
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_ALLVALUES, ");
  }else if(STReq(data, METADATA_VALUE_OBSERVER_DATA_LEVEL_TAGVALUES)){
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_TAGVALUES, ");
  }else{
    fprintf(srcFile, "SNET_OBSERVERS_DATA_LEVEL_LABELS, ");
  }

  CODEFILEwriteNewlineAndIndent();
  if(code != NULL){
    fprintf(srcFile, "\"%s\");", code);
  }else {
    fprintf(srcFile, "NULL);");
  }

  decreaseIndentLevels(6);

  CODEFILEwriteNewline();
  CODEFILEwriteOutBufReturn();
  CODEFILEwriteScopeStop();
}

void CODEFILEwriteObserverAuxStart(const char *net)
{
  fprintf(srcFile, "\nstatic snet_stream_t *SNet____OBSERVER__AUX__%s(snet_stream_t *in_buf, snet_info_t *info, int location)\n{", net);
  increaseIndentLevel();
}

void CODEFILEwriteObserverSnetEntity(const char *pkg, const char *entity)
{
  CODEFILEwriteNewlineAndIndent();
  if(pkg == NULL) {
    fprintf(srcFile, "&SNet____OBSERVED__%s", entity);
  }
  else{
    fprintf(srcFile, "&SNet____OBSERVED__%s___%s", pkg, entity);
  }
}

void CODEFILEwriteObserverBeforeSnetEntity(const char *pkg, const char *entity)
{
  CODEFILEwriteNewlineAndIndent();
  if(pkg == NULL) {
    fprintf(srcFile, "&SNet____OBSERVER__BEFORE__%s", entity);
  }
  else{
    fprintf(srcFile, "&SNet____OBSERVER_BEFORE__%s___%s", pkg, entity);
  }
}

void CODEFILEwriteObserverAfterSnetEntity(const char *pkg, const char *entity)
{
  CODEFILEwriteNewlineAndIndent();
  if(pkg == NULL) {
    fprintf(srcFile, "&SNet____OBSERVER__AFTER__%s", entity);
  }
  else{
    fprintf(srcFile, "&SNet____OBSERVER__AFTER__%s___%s", pkg, entity);
  }
}

void CODEFILEwriteObserverAuxSnetEntity(const char *pkg, const char *entity)
{
  CODEFILEwriteNewlineAndIndent();
  if(pkg == NULL) {
    fprintf(srcFile, "&SNet____OBSERVER__AUX__%s", entity);
  }
  else{
    fprintf(srcFile, "&SNet____OBSERVER__AUX__%s___%s", pkg, entity);
  }
}

void CODEFILEwriteSnetLabelsDefinition()
{
  fprintf(hdrFile, "\nextern char *snet_%s_labels[];\n", global.filebase);
}

void CODEFILEwriteSnetLabelsStart()
{
  fprintf(srcFile, "\nchar *snet_%s_labels[] = {\n\t\"E__%s__None\"", global.filebase, global.filebase);
}

void CODEFILEwriteFieldLabel(const char *pkg, const char *field)
{
  if(pkg == NULL) {
    fprintf(srcFile, ",\n\t\"%s\"", field);
  }
}

void CODEFILEwriteStagLabel(const char *pkg, const char *stag)
{
  if(pkg == NULL) {
    fprintf(srcFile, ",\n\t\"%s\"", stag);
  }
}

void CODEFILEwriteBtagLabel(const char *pkg, const char *btag)
{
  if(pkg == NULL) {
    fprintf(srcFile, ",\n\t\"%s\"", btag);
  }
}

void CODEFILEwriteSnetLabelsEnd()
{
  fprintf(srcFile, "};\n");
}

void CODEFILEwriteSnetInterfacesDefinition()
{
  fprintf(hdrFile, "\nextern char *snet_%s_interfaces[];\n", global.filebase);
}

void CODEFILEwriteSnetInterfacesStart()
{
  fprintf(srcFile, "\nchar *snet_%s_interfaces[] = {", global.filebase);
}

void CODEFILEwriteInterface(const char *interface)
{
  fprintf(srcFile, "\n\t\"%s\"", interface);
}

void CODEFILEwriteSnetInterfacesEnd()
{
  fprintf(srcFile, "};\n");
}

void CODEFILEwriteMainStart()
{
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "int SNetMain__%s(int argc, char* argv[])\n{", global.filebase);

  increaseIndentLevel();
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "int ret = 0;\n");
}

void CODEFILEwriteMainInterfaceInit(const char *interface)
{
  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "%sInit(I__%s__%s, %d);", interface, global.filebase, interface, global.distribution_lib);

  CODEFILEwriteNewlineAndIndent();
}

void CODEFILEwriteMainEnd()
{
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "ret = SNetInRun(argc, argv,");

  increaseIndentLevels(6);

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "snet_%s_labels,", global.filebase);

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNET__%s__NUMBER_OF_LABELS,", global.filebase);

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "snet_%s_interfaces,", global.filebase);

  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNET__%s__NUMBER_OF_INTERFACES,", global.filebase);

  CODEFILEwriteNewlineAndIndent();

  fprintf(srcFile, "SNet__%s___%s);\n",
	  global.filebase, global.filebase);


  decreaseIndentLevels(6);
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "SNetInterfacesDestroy();\n");
  CODEFILEwriteNewlineAndIndent();
  fprintf(srcFile, "return( ret);");
  decreaseIndentLevel();

  CODEFILEwriteNewlineAndIndent();
  CODEFILEwriteScopeStop();
}

void CODEFILEwriteBoxWrap( const char *wrap)
{
  fprintf( srcFile, "\n%s", wrap);
}

void CODEFILEwriteLocation(int location)
{
  fprintf(srcFile, ", info");

  if (global.enable_dist_snet && location >= 0) {
    fprintf(srcFile, ", %d", location);
  } else {
    fprintf(srcFile, ", location");
  }
}

void CODEFILEwriteSnetEntityName(const char *pkg, const char *entity)
{
  if(pkg == NULL) {
    fprintf(srcFile, "&SNet__%s", entity);
  }
  else{
    fprintf(srcFile, "&SNet__%s___%s", pkg, entity);
  }
}

void CODEFILEwriteNetToIdFunStart()
{
  fprintf(srcFile, "\nint SNetNetToId(snet_startup_fun_t fun)\n{\n  ");
}

void CODEFILEwriteIdToNetFunStart()
{
  fprintf(srcFile, "\nsnet_startup_fun_t SNetIdToNet(int id)\n{\n  ");
}

void CODEFILEwriteNetToId(int count, const char *pkg, const char *entity)
{
  if (count > 2) fprintf(srcFile, " else ");
  fprintf(srcFile, "if (fun == ");
  CODEFILEwriteSnetEntityName(pkg, entity);
  fprintf(srcFile, ") {\n    return %d;\n  }", count);
}

void CODEFILEwriteIdToNet(int count, const char *pkg, const char *entity)
{
  if (count > 2) fprintf(srcFile, " else ");
  fprintf(srcFile, "if (id == %d) {\n    return ", count);
  CODEFILEwriteSnetEntityName(pkg, entity);
  fprintf(srcFile, ";\n  }");
}

void CODEFILEwriteNetToIdFunEnd()
{
  fprintf(srcFile, "\n\n  return -1;\n}\n");
}

void CODEFILEwriteIdToNetFunEnd()
{
  fprintf(srcFile, "\n\n  return NULL;\n}\n");
}
